version: "2"
services:
  affablebean-db:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: shota
      MYSQL_PASSWORD: shota77ben10
      MYSQL_ROOT_PASSWORD: root
